title: Dev-Proxy Documentation
description: A powerful development proxy server with rule-based request/response manipulation
baseurl: ""
url: "https://nev3rm0re.github.io/dev-proxy"

# Theme
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Index settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Ensure index.md is treated as the homepage
index_files:
  - index.md
  - index.html

# Navigation
header_pages:
  - README.md
  - rules-api.md
  - use-cases.md

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 